# Generated by Django 4.2.2 on 2023-09-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
